import Heading from "../../../_components/Heading"
import Info from "@/app/_components/Info"
import {disclaimerDescription, privacyPolicyDescription} from "../../../../constants/constant"

import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Disclaimer & Privacy Policy',
  description: 'Generated by create next app',
}


const page = () => {
  return (
    <div className="flex flex-col lg:px-[124px] md:px-[72px] sm:px-[40px] px-[36px] lg:py-20 md:py-10 py-8 ">
        <div id="disclaimer"  className=" flex justify-center ">
            <Heading>Disclaimer</Heading>
        </div>
        <div className="lg:mt-4 mt-0 ">
        <Info info={disclaimerDescription.info} image={disclaimerDescription.image} direction="rtl"/>
        </div>
        <div  id="privacyPolicy" className="flex justify-center mt-20">
           <Heading>Privacy Policy</Heading>
        </div>
        <div className="lg:mt-4">
            <Info info={privacyPolicyDescription.info} image={privacyPolicyDescription.image} direction="ltr"/>
        </div>
    </div>
  )
}

export default page