import UpcomingEvent from "../_components/UpcomingEvent";
import PastEvents from "../_components/PastEvents";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: 'Events',
  description: 'Generated by create next app',
}

const EventsPage = () => {
  return (
    <div className="lg:py-20 md:py-10 py-8 flex flex-col justify-center items-center">
      <UpcomingEvent/>
      <div className="lg:mt-[200px] md:mt-[140px] mt-[80px]">
        <div className=" mb-24">
      <PastEvents/>
        </div>
      </div>
    </div>
  );
};

export default EventsPage;
